# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_event_file:
    runs-on: ubuntu-latest
    steps:
      - name: 'deps'
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: pushed_at
        run: cat $GITHUB_EVENT_PATH | jq .pull_request.head.repo.pushed_at
      - name: event_md5
        run: md5sum $GITHUB_EVENT_PATH

